name: FFXIV Data Downloader

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

jobs:
  download_files:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retrieve FFXIV Data Cache
        uses: actions/cache@v4
        with:
          path: exd-data
          key: ffxiv-exd-data-${{ hashFiles('exd-data/.cachemeta.json') }}
          restore-keys: |
            ffxiv-exd-data-

      - name: Download EXD Files
        id: download
        uses: WorkingRobot/ffxiv-downloader@v8
        with:
          output-path: exd-data
          regex: '^sqpack\/ffxiv\/0a0000\..+$'
          verbose: true

      - name: Create GitHub Release if updated and triggered by tag
        if: |
          startsWith(github.ref, 'refs/tags/') &&
          steps.download.outputs.updated == 'true'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: 国际服原文件备份 ${{ steps.download.outputs.version }}
          files: exd-data/**
          draft: false
          prerelease: false

      - name: Upload Downloaded Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffxiv-exd-files
          path: exd-data
          retention-days: 7
